### ISSUE TITLE
pkg-config variable version-scripts is invisible

### ISSUE THREAD

**Issue by AdrianVovk** [c-util/c-stdaux#17]
Seems like pkgconf does _not_ like dashes in variable names. For instance:

```
$ pkg-config --variable=version-scripts /usr/lib/pkgconfig/libcstdaux-1.pc 

$
```

For this .pc file:

```
prefix=/usr
includedir=${prefix}/include

cflags=-D_GNU_SOURCE -Wno-maybe-uninitialized -Wno-unused-parameter -Wno-error=type-limits -Wno-error=missing-field-initializers -Wdate-time -Wdeclaration-after-statement -Wlogical-op -Wmissing-include-dirs -Wmissing-noreturn -Wnested-externs -Wredundant-decls -Wshadow -Wstrict-aliasing=3 -Wsuggest-attribute=noreturn -Wundef -Wwrite-strings
version-scripts=yes

Name: libcstdaux
Description: Auxiliary macros and functions for the C standard library
Version: 1.4.0
Cflags: -I${includedir}
```

If I get rid of the dash in the variable name, pkg-config can suddenly find the variable. I can reproduce this w/ pkgconf 1.9.6 and also 2.0.2, so it doesn't seem to be a pkgconf bug that was introduced at any point recently.

Symptom that led me to this discovery: `src/meson.build:22:31: ERROR: Could not get pkg-config variable and no default provided for <PkgConfigDependency libcstdaux-1: True None>` errors from my distro's packaging of `libcutf8` and similar. Only relevant thing that changed is a meson upgrade from 1.2.1 to 1.3.0; perhaps the handling of defaults changed in meson and exposed this bug? I'm not sure

**Comment by dvdhrm** [comment]
Indeed. Nice catch! I pushed a fix that provides `version_scripts` alongside the old variables. It will be included in the upcoming 1.5.0 release. We will have to update the dependent projects, though.

Let me know if anything is missing! Thanks a lot!
